createf90types_SOURCES   = createf90types.c
createf90types_LDADD     = ../../util/mtest.o

../../util/mtest.o: 
	(cd ../../util && $(MAKE) mtest.o)

smvarSubdir_do_dependencies=no
smvar_dependenciesDummy=yes
