/* mpid_locksconf.h.  Generated by configure.  */
/* mpid_locksconf.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the `compare_and_swap' function. */
/* #undef HAVE_COMPARE_AND_SWAP */

/* Define to 1 if you have the `mutex_init' function. */
/* #undef HAVE_MUTEX_INIT */

/* Define to 1 if you have the <pthread.h> header file. */
#define HAVE_PTHREAD_H 1

/* Define to 1 if you have the `pthread_mutexattr_init' function. */
#define HAVE_PTHREAD_MUTEXATTR_INIT 1

/* Define to 1 if you have the `pthread_mutexattr_setpshared' function. */
#define HAVE_PTHREAD_MUTEXATTR_SETPSHARED 1

/* Define to 1 if you have the <sched.h> header file. */
#define HAVE_SCHED_H 1

/* Define to 1 if you have the `sched_yield' function. */
#define HAVE_SCHED_YIELD 1

/* Define to 1 if you have the `select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the `sleep' function. */
#define HAVE_SLEEP 1

/* Use inline spin locks on SPARC architectures */
/* #undef HAVE_SPARC_INLINE_PROCESS_LOCKS */

/* Define to 1 if you have the `usleep' function. */
#define HAVE_USLEEP 1

/* Define to 1 if you have the `yield' function. */
/* #undef HAVE_YIELD */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""
