SUBDIRS = util attr datatype coll pt2pt info init comm topo rma spawn io ext

# A special testing target to simplify testing just the F77 code
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=@MPIEXEC@ \
		   -xmlfile=summary.xml

smvarSubdir_do_dependencies=no
smvar_dependenciesDummy=yes
