INCLUDES = -I../include -I${top_srcdir}/include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

adderr_SOURCES = adderr.c
errstring_SOURCES = errstring.c
errcode_SOURCES = errcode.c errmsg.c
errring_SOURCES = errring.c
commcall_SOURCES = commcall.c
winerr_SOURCES = winerr.c
winerr2_SOURCES = winerr2.c
errfatal_SOURCES = errfatal.c

EXTRA_PROGRAMS = errcode errring

../util/mtest.o: 
	(cd ../util && make mtest.o)

testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=$(bindir)/mpiexec \
		   	-xmlfile=summary.xml
