INCLUDES = -I../include -I${srcdir}/../include
LDADD = ../util/mtest.o
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

attrt_SOURCES = attrt.c
attric_SOURCES = attric.c
attrerr_SOURCES = attrerr.c
attrerrcomm_SOURCES = attrerrcomm.c
attrerrtype_SOURCES = attrerrtype.c
attrorder_SOURCES = attrorder.c
attrordercomm_SOURCES = attrordercomm.c
attrordertype_SOURCES = attrordertype.c
attrorderwin_SOURCES = attrorderwin.c
baseattr2_SOURCES = baseattr2.c
baseattrcomm_SOURCES = baseattrcomm.c
baseattrwin_SOURCES = baseattrwin.c
fkeyval_SOURCES = fkeyval.c
fkeyvalcomm_SOURCES = fkeyvalcomm.c
fkeyvaltype_SOURCES = fkeyvaltype.c
fkeyvalwin_SOURCES = fkeyvalwin.c 

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=$(bindir)/mpiexec \
		   	-xmlfile=summary.xml
