SUBDIRS = util attr pt2pt init info comm coll datatype io rma spawn

# A special testing target to simplify testing just the C++ code
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=@MPIEXEC@ \
		   -xmlfile=summary.xml


smvarSubdir_do_dependencies=no
smvar_dependenciesDummy=yes
