INCLUDES = -I../../../../../../include -I${master_top_srcdir}/src/include
lib${MPILIBNAME}_a_SOURCES = \
 ch3_finalize.c ch3_init.c \
 ch3_isend.c ch3_isendv.c ch3_istartmsg.c ch3_istartmsgv.c \
 ch3_request.c \
 ch3_progress.c ch3_cancel_send.c ch3_read_progress.c \
 ch3_comm_spawn_multiple.c ch3_comm_accept.c ch3_comm_connect.c ch3_open_port.c \
 ch3_abort.c ch3_get_business_card.c
