SUBDIRS = util timer attr coll datatype pt2pt info comm rma spawn topo io ext \
	init misc f90types

# A special testing target to simplify testing just the Fortran 90 code
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=@MPIEXEC@ \
		   -xmlfile=summary.xml

smvarSubdir_do_dependencies=no
smvar_dependenciesDummy=yes
