SUBDIRS = util timer attr coll datatype pt2pt info comm rma spawn topo io ext init
# Other dirs: misc (sizeof, only in more complete F90 implementation)

# A special testing target to simplify testing just the Fortran 90 code
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=$(bindir)/mpiexec \
		   -xmlfile=summary.xml
